### ISSUE TITLE
Purity and safety

### ISSUE THREAD

**Issue by ZILtoid1991** [Sandman83/vebtree#2]
How much of this library is pure and/or safe?

I would like to use it (even replacing my own implementation of a binary search tree), but I don't know how much of it is safe and/or pure. Lack of purity would mean I have to mark a lot of my code that otherwise doesn't access any static fields as impure.

**Comment by Sandman83** [comment]
Hi there! 
Cool, thanks for the interest! 
I managed to mark almost all functions as pure. I. e. the opEquals operators and the opApplys would need more effort because I would have to define always two versions (for a pure and for non-pure delegates, which are passed to opApply). So far, I did so only for gc/non-gc. 
Look at [this branch](https://github.com/Sandman83/vebtree/tree/feature/purity) for comparison.
Not sure about your use case. Do you need also the comparison operators to be pure? 

The question about safety is simpler: according to [this forum post](https://forum.dlang.org/post/mkptkaijuufauqjxuxsf@forum.dlang.org) the library can be compiled as @safe by default.

**Comment by ZILtoid1991** [comment]
This is sufficient for now.

Could you make a new release? You can make it as a pre-release if you're not too confident.

**Comment by Sandman83** [comment]
done. tag: 0.13.1. 
I still do not really know how to make opEquals pure in this case and added a comment about this in the code. If you do - hints are appreciated...
I assume this ticket can be closed now?

**Comment by ZILtoid1991** [comment]
Yeah, I'll close it now.
